language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: bionic
    - os: linux
      compiler: clang
      dist: bionic
    - os: osx
      compiler: clang
      before_script:
        - export PATH="/usr/local/opt/bison/bin:$PATH"
      addons:
        homebrew:
          update: true
          packages:
            - bison

addons:
  apt:
    packages:
      - libboost-filesystem-dev
      - libboost-iostreams-dev
      - libboost-program-options-dev
      - libboost-system-dev

script:
  - make -j4
  - make -j4 check

notifications:
  email:
    recipients:
      - xaizek@posteo.net
